/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatservergui;

/**
 *
 * @author Kruger
 */
public class ClientGUI extends javax.swing.JFrame {

    /**
     * Creates new form ClientGUI
     */
    private String msg_out, cgname,cgpass,gname,gpass,fname = "";
    public ClientGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        msg_area = new javax.swing.JTextArea();
        msg_text = new javax.swing.JTextField();
        msg_send = new javax.swing.JButton();
        login_name = new javax.swing.JTextField();
        create_name = new javax.swing.JTextField();
        create_pass = new javax.swing.JTextField();
        login_pass = new javax.swing.JTextField();
        create_send = new javax.swing.JButton();
        login_send = new javax.swing.JButton();
        download_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        msg_area.setColumns(20);
        msg_area.setRows(5);
        jScrollPane1.setViewportView(msg_area);

        msg_text.setText("Type a message...");
        msg_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_textActionPerformed(evt);
            }
        });

        msg_send.setText("Send");
        msg_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_sendActionPerformed(evt);
            }
        });

        login_name.setText("Enter valid group name");

        create_name.setText("Create group name");

        create_pass.setText("Create group password");
        create_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_passActionPerformed(evt);
            }
        });

        login_pass.setText("Group password");
        login_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_passActionPerformed(evt);
            }
        });

        create_send.setText("Create group");
        create_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_sendActionPerformed(evt);
            }
        });

        login_send.setText("Enter group");
        login_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_sendActionPerformed(evt);
            }
        });

        download_button.setText("Download File");
        download_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                download_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(msg_text, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(msg_send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(login_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(create_name, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(create_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(login_pass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(create_send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(login_send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(download_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(msg_send, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(msg_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(login_name)
                    .addComponent(login_pass)
                    .addComponent(login_send, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(create_name)
                    .addComponent(create_pass)
                    .addComponent(create_send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(download_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Sends message to the message area.
     * @param evt 
     */
    private void msg_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_sendActionPerformed
        try{
        msg_out = msg_text.getText().trim();
        msg_text.setText("");
        msg_area.setText(msg_area.getText().trim()+"\n"+msg_out);
        char[] cAr = msg_out.toCharArray();
        if(cAr[0] == '-' && cAr[1] == 'f')
        {
            fname = msg_out.substring(3);
            msg_area.setText(msg_area.getText().trim()+"\nFile received: "+fname);
        }
        }
        catch(Exception e){
            msg_area.setText(msg_area.getText().trim()+"\n"+e.getMessage()); // Print error message
        }
    }//GEN-LAST:event_msg_sendActionPerformed
    
    /**
     * Returns the last message sent.
     * @return 
     */
    private String getMessage()
    {
        return msg_out;
    }
    
    /**
     * Sends message to the message area.
     * @param evt 
     */
    private void msg_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_textActionPerformed
        try{
        msg_out = msg_text.getText().trim();
        msg_text.setText("");
        msg_area.setText(msg_area.getText().trim()+"\n"+msg_out);
        char[] cAr = msg_out.toCharArray();
        if(cAr[0] == '-' && cAr[1] == 'f')
        {
            fname = msg_out.substring(3);
            msg_area.setText(msg_area.getText().trim()+"\nFile received: "+fname);
        }
        }
        catch(Exception e){
            msg_area.setText(msg_area.getText().trim()+"\n"+e.getMessage()); // Print error message
        }
    }//GEN-LAST:event_msg_textActionPerformed
    
    /**
     * Collects login details and opens new group chat.
     * @param evt 
     */
    private void login_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_sendActionPerformed
        try{
        gname = login_name.getText().trim();
        gpass = login_pass.getText().trim();
        login_name.setText("");
        login_pass.setText("");
        msg_area.setText("");}
        catch(Exception e){
            msg_area.setText(msg_area.getText().trim()+"\n"+e.getMessage()); // Print error message
        }
    }//GEN-LAST:event_login_sendActionPerformed
    
    
    /**
     * Creates group name and password.
     * @param evt 
     */
    private void create_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_sendActionPerformed
        try{
        cgname = create_name.getText().trim();
        cgpass = create_pass.getText().trim();
        create_name.setText("");
        create_pass.setText("");
        msg_area.setText("");}
        catch(Exception e){
            msg_area.setText(msg_area.getText().trim()+"\n"+e.getMessage()); // Print error message
        }
    }//GEN-LAST:event_create_sendActionPerformed
    
    /**
     * Collects login details and opens new group chat.
     * @param evt 
     */
    private void login_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_passActionPerformed
        try{
        gname = login_name.getText().trim();
        gpass = login_pass.getText().trim();
        login_name.setText("");
        login_pass.setText("");
        msg_area.setText("");}
        catch(Exception e){
            msg_area.setText(msg_area.getText().trim()+"\n"+e.getMessage()); // Print error message
        }
    }//GEN-LAST:event_login_passActionPerformed
    
    /**
     * Creates and saves Group-Password combination.
     * @param evt 
     */
    private void create_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_passActionPerformed
        try{
        cgname = create_name.getText().trim();
        cgpass = create_pass.getText().trim();
        create_name.setText("");
        create_pass.setText("");
        msg_area.setText("");}
        catch(Exception e){
            msg_area.setText(msg_area.getText().trim()+"\n"+e.getMessage()); // Print error message
        }
    }//GEN-LAST:event_create_passActionPerformed

    private void download_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_download_buttonActionPerformed
        try{
        if(!fname.equals(""))
        {
            // Download file fname
            msg_area.setText(msg_area.getText().trim()+"\n"+fname+" downloaded");
        }
        else{
            msg_area.setText(msg_area.getText().trim()+"\nNo file selected");           
        }}catch(Exception e){
            msg_area.setText(msg_area.getText().trim()+"\n"+e.getMessage()); // Print error message            
        }
    }//GEN-LAST:event_download_buttonActionPerformed
    
    /**
     * Returns the Group name.
     * @return 
     */
    private String getGroupName()
    {
        return gname;
    }
    
    /**
     * Returns the group password.
     * @return 
     */
    private String getGroupPassword()
    {
        return gpass;
    }
    
    /**
     * Returns the new group name.
     * @return 
     */
    private String getNewGroupName()
    {
        return cgname;
    }
    
    /**
     * Returns the new group password.
     * @return 
     */
    private String getNewGroupPassword()
    {
        return cgpass;
    }
    
    /**
     * Adds a message to the text area.
     * @param message 
     */
    private void addMessage(String message)
    {
        msg_area.setText(msg_area.getText().trim()+"\n"+message);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGUI().setVisible(true);
                msg_area.setEditable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField create_name;
    private javax.swing.JTextField create_pass;
    private javax.swing.JButton create_send;
    private javax.swing.JButton download_button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField login_name;
    private javax.swing.JTextField login_pass;
    private javax.swing.JButton login_send;
    private static javax.swing.JTextArea msg_area;
    private javax.swing.JButton msg_send;
    private javax.swing.JTextField msg_text;
    // End of variables declaration//GEN-END:variables
}
