/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kruger
 */
public class Login_create_user extends javax.swing.JFrame {

    /**
     * Creates new form Login_create_user
     */
    private String l_user,l_pass,c_user,c_pass = "";
    public Login_create_user() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lu_txt = new javax.swing.JTextField();
        lp_txt = new javax.swing.JTextField();
        cu_txt = new javax.swing.JTextField();
        cp_txt = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        create = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lu_txt.setText("Username");
        lu_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lu_txtActionPerformed(evt);
            }
        });

        lp_txt.setText("Password");
        lp_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lp_txtActionPerformed(evt);
            }
        });

        cu_txt.setText("Create username");
        cu_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cu_txtActionPerformed(evt);
            }
        });

        cp_txt.setText("Create Password");
        cp_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_txtActionPerformed(evt);
            }
        });

        login.setText("Login user");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        create.setText("Create user");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cu_txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(lu_txt, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lp_txt)
                    .addComponent(cp_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(create, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lp_txt)
                    .addComponent(lu_txt)
                    .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cu_txt)
                    .addComponent(cp_txt)
                    .addComponent(create, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lu_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lu_txtActionPerformed
        try{
        l_user = lu_txt.getText().trim();
        l_pass = lp_txt.getText().trim();
        }
        catch(Exception e){
            // Maybe do something?
        }
    }//GEN-LAST:event_lu_txtActionPerformed

    private void lp_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lp_txtActionPerformed
        try{
        l_user = lu_txt.getText().trim();
        l_pass = lp_txt.getText().trim();
        }
        catch(Exception e){
            // Maybe do something?
        }
    }//GEN-LAST:event_lp_txtActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        try{
        l_user = lu_txt.getText().trim();
        l_pass = lp_txt.getText().trim();
        }
        catch(Exception e){
            // Maybe do something?
        }
    }//GEN-LAST:event_loginActionPerformed

    private void cu_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cu_txtActionPerformed
        try{
        c_user = cu_txt.getText().trim();
        c_pass = cp_txt.getText().trim();
        }
        catch(Exception e){
            // Maybe do something?
        }
    }//GEN-LAST:event_cu_txtActionPerformed

    private void cp_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_txtActionPerformed
        try{
        c_user = cu_txt.getText().trim();
        c_pass = cp_txt.getText().trim();
        }
        catch(Exception e){
            // Maybe do something?
        }
    }//GEN-LAST:event_cp_txtActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        try{
        c_user = cu_txt.getText().trim();
        c_pass = cp_txt.getText().trim();
        }
        catch(Exception e){
            // Maybe do something?
        }
    }//GEN-LAST:event_createActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_create_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_create_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_create_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_create_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_create_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cp_txt;
    private javax.swing.JButton create;
    private javax.swing.JTextField cu_txt;
    private javax.swing.JButton login;
    private javax.swing.JTextField lp_txt;
    private javax.swing.JTextField lu_txt;
    // End of variables declaration//GEN-END:variables
}
